apiVersion: v1
kind: Service
metadata:
  name: onlinefs-monitor
  namespace: hopsworks
spec:
  selector:
    app: onlinefs
  ports:
  - protocol: TCP
    name: monitor
    port: 12800
    targetPort: monitor
  type: ClusterIP